/* =========================================================
   Banco de preguntas y lógica de exámenes — Autoescola Manel
   Preguntas de elaboración propia siguiendo el estilo y la
   normativa general de tráfico (RGC/DGT). No es el banco
   oficial de la DGT.
   ========================================================= */

export const CATS = {
  senyals_reglament: "Senyals de reglamentació",
  senyals_perill: "Senyals de perill",
  senyals_indicacio: "Senyals d'indicació",
  marques_vials: "Marques vials",
  normes_general: "Normes generals de circulació",
  alcohol_drogues: "Alcohol i drogues",
  seguretat_passiva: "Seguretat passiva",
  llums: "Enllumenat i llums",
  autopista: "Autopistes i autovies",
  documentacio: "Documentació i assegurança",
  mecanica: "Manteniment i mecànica",
  primers_auxilis: "Primers auxilis",
  factor_humans: "Factor humà",
  sancions: "Sancions i carnet per punts",
  estacionament: "Aturada i estacionament",
  usuaris_vulnerables: "Vianants, ciclistes i VMP",
  prioritat: "Prioritat de pas",
  carrils: "Carrils especials (VAO, reversible, addicional)",
  velocitat: "Velocitats i límits",
};

export const Q = [
// ---- senyals_reglament ----
{c:"senyals_reglament",img:"/senyals/senyals-reglament-01.svg",imgAlt:"Una señal circular de fondo blanco y borde rojo, sin ningún otro…",q:"Una señal circular de fondo blanco y borde rojo, sin ningún otro dibujo, indica:",o:["Prohibido el paso a todo vehículo","Dirección obligatoria","Fin de todas las prohibiciones","Ceda el paso"],a:0,e:"El círculo blanco con borde rojo y sin símbolo es la señal de entrada prohibida a todo vehículo."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-02.svg",imgAlt:"Una señal circular de fondo azul con una flecha blanca indica",q:"Una señal circular de fondo azul con una flecha blanca indica:",o:["Dirección prohibida","Sentido obligatorio en la dirección indicada","Calle sin salida","Zona peatonal"],a:1,e:"Las señales azules circulares marcan obligaciones, en este caso seguir la dirección de la flecha."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-03.svg",imgAlt:"La señal de STOP obliga a",q:"La señal de STOP obliga a:",o:["Reducir la velocidad sin detenerse si no viene nadie","Detenerse completamente aunque no venga ningún vehículo","Detenerse solo de noche","Tocar el claxon antes de cruzar"],a:1,e:"El STOP obliga siempre a una detención total antes de la línea de detención, haya tráfico o no."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-04.svg",imgAlt:"Un triángulo invertido de borde rojo significa",q:"Un triángulo invertido de borde rojo significa:",o:["Peligro genérico","Ceda el paso","Prohibido adelantar","Intersección con prioridad"],a:1,e:"El triángulo invertido es la señal de Ceda el paso."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-05.svg",imgAlt:"La señal circular azul con una bicicleta blanca indica",q:"La señal circular azul con una bicicleta blanca indica:",o:["Prohibido circular en bicicleta","Vía reservada a ciclistas","Peligro por presencia de ciclistas","Zona de alquiler de bicicletas"],a:1,e:"Las señales azules de obligación con un símbolo indican la vía o carril reservado a ese tipo de usuario."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-06.svg",imgAlt:"Una señal circular de fondo blanco con el número 50 dentro de un…",q:"Una señal circular de fondo blanco con el número 50 dentro de un borde rojo significa:",o:["Velocidad mínima de 50 km/h","Fin de la limitación de 50 km/h","Velocidad máxima autorizada de 50 km/h","Distancia mínima de 50 m entre vehículos"],a:2,e:"El círculo con borde rojo y un número indica la velocidad máxima permitida en ese tramo."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-07.svg",imgAlt:"Cuando una señal de limitación de velocidad va acompañada de una…",q:"Cuando una señal de limitación de velocidad va acompañada de una banda diagonal negra sobre el mismo número, significa:",o:["Que la limitación es solo para camiones","Fin de la prohibición o restricción indicada","Que hay que reducir aún más la velocidad","Que la velocidad mínima es la indicada"],a:1,e:"La banda diagonal negra sobre la señal indica el final de la restricción."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-08.svg",imgAlt:"La señal circular blanca con borde rojo y la silueta de un camión…",q:"La señal circular blanca con borde rojo y la silueta de un camión significa:",o:["Prohibido el adelantamiento a camiones","Entrada prohibida a vehículos de mercancías del tipo indicado","Zona de carga y descarga","Paso obligatorio para camiones"],a:1,e:"Es una señal de prohibición de entrada específica para el tipo de vehículo representado."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-09.svg",imgAlt:"Una señal rectangular azul con una 'P' blanca indica",q:"Una señal rectangular azul con una 'P' blanca indica:",o:["Prioridad de paso","Zona de estacionamiento permitido","Prohibido detenerse","Peligro de pendiente"],a:1,e:"La 'P' blanca sobre fondo azul señaliza una zona donde se permite estacionar."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-10.svg",imgAlt:"Una señal circular de fondo blanco y borde rojo con el dibujo de dos…",q:"Una señal circular de fondo blanco y borde rojo con el dibujo de dos flechas, una hacia arriba y otra hacia abajo, indica:",o:["Prohibido adelantar","Doble sentido de circulación","Sentido único en ese carril","Prohibido el cambio de sentido"],a:1,e:"Esta señal advierte de que la vía pasa a tener doble sentido de circulación."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-11.svg",imgAlt:"La señal circular azul con el dibujo de un peatón indica",q:"La señal circular azul con el dibujo de un peatón indica:",o:["Paso de peatones obligatorio 100 m más adelante","Camino obligatorio para peatones (vía o zona reservada)","Prohibido el paso de peatones","Zona de juegos"],a:1,e:"Es una señal de obligación que indica una vía o zona reservada exclusivamente a peatones."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-12.svg",imgAlt:"Una señal circular blanca con borde rojo y la silueta de una…",q:"Una señal circular blanca con borde rojo y la silueta de una motocicleta significa:",o:["Aparcamiento reservado para motos","Entrada prohibida a motocicletas","Zona de lavado de motos","Velocidad mínima para motos"],a:1,e:"Es una señal de prohibición de entrada específica para el tipo de vehículo representado, en este caso motocicletas."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-13.svg",imgAlt:"La señal 'Ceda el paso' se diferencia del 'STOP' en que",q:"La señal 'Ceda el paso' se diferencia del 'STOP' en que:",o:["Son exactamente equivalentes","Con 'Ceda el paso' solo hay que detenerse si es necesario para no interrumpir el tráfico preferente","El 'Ceda el paso' obliga siempre a detención total","El 'STOP' solo se aplica de noche"],a:1,e:"A diferencia del STOP, en el 'Ceda el paso' la detención solo es obligatoria si es necesaria para no interferir en el tráfico de la vía preferente."},
{c:"senyals_reglament",img:"/senyals/senyals-reglament-14.svg",imgAlt:"Una señal circular blanca con borde rojo que muestra dos vehículos…",q:"Una señal circular blanca con borde rojo que muestra dos vehículos uno al lado del otro significa:",o:["Prohibido adelantar","Carretera de doble carril obligatorio","Zona de adelantamiento permitido únicamente","Obligatorio circular en fila"],a:0,e:"Esta señal indica la prohibición de adelantamiento para determinados vehículos."},

// ---- senyals_perill ----
{c:"senyals_perill",img:"/senyals/senyals-perill-01.svg",imgAlt:"Las señales de peligro (triángulo amarillo/rojo) deben colocarse, en…",q:"Las señales de peligro (triángulo amarillo/rojo) deben colocarse, en carretera convencional, a una distancia del peligro de:",o:["Justo al lado del peligro","Entre 150 y 250 m antes","No hace falta ninguna distancia fija","Solo después del peligro"],a:1,e:"En vías convencionales la señal de peligro suele situarse unos 150-250 m antes para dar tiempo de reacción."},
{c:"senyals_perill",img:"/senyals/senyals-perill-02.svg",imgAlt:"Un triángulo con el dibujo de una flecha que se curva bruscamente…",q:"Un triángulo con el dibujo de una flecha que se curva bruscamente indica:",o:["Curva peligrosa","Carretera de doble sentido","Fin de la autopista","Zona escolar"],a:0,e:"Advierte de la proximidad de una curva o sucesión de curvas peligrosas."},
{c:"senyals_perill",img:"/senyals/senyals-perill-03.svg",imgAlt:"Un triángulo con el dibujo de dos niños indica",q:"Un triángulo con el dibujo de dos niños indica:",o:["Zona de juego infantil lejana","Proximidad de un centro escolar o zona con presencia de niños","Obligación de llevar a los niños con cinturón","Prohibido el paso a niños solos"],a:1,e:"Advierte de la proximidad de una zona con posible presencia de niños, como colegios."},
{c:"senyals_perill",img:"/senyals/senyals-perill-04.svg",imgAlt:"Un triángulo con una cruz (aspa) indica",q:"Un triángulo con una cruz (aspa) indica:",o:["Peligro por cruce con vía sin prioridad","Paso a nivel sin barreras","Fin de toda prohibición","Zona de obras"],a:1,e:"Esta señal avisa de un paso a nivel de ferrocarril sin barreras."},
{c:"senyals_perill",img:"/senyals/senyals-perill-05.svg",imgAlt:"La señal de peligro con el dibujo de una calzada resbaladiza significa",q:"La señal de peligro con el dibujo de una calzada resbaladiza significa:",o:["Firme en mal estado solo en caso de lluvia","Calzada resbaladiza; hay que reducir la velocidad y evitar frenazos bruscos","Prohibido circular con neumáticos lisos","Zona de lavado de vehículos"],a:1,e:"Indica riesgo de pérdida de adherencia; hay que moderar la velocidad y evitar maniobras bruscas."},
{c:"senyals_perill",img:"/senyals/senyals-perill-06.svg",imgAlt:"Un triángulo con el dibujo de animales domésticos indica",q:"Un triángulo con el dibujo de animales domésticos indica:",o:["Zona de pastoreo obligatoria","Posible presencia de animales en la calzada","Prohibido el transporte de animales","Servicio veterinario cercano"],a:1,e:"Advierte de que puede haber ganado o animales cruzando o cerca de la vía."},
{c:"senyals_perill",img:"/senyals/senyals-perill-07.svg",imgAlt:"La señal de peligro que muestra un cruce en forma de cruz simple…",q:"La señal de peligro que muestra un cruce en forma de cruz simple indica:",o:["Intersección con una vía de características similares, sin prioridad clara","Prohibido girar","Rotonda cercana","Fin de la autovía"],a:0,e:"Avisa de una intersección donde ninguna de las vías tiene preferencia marcada por señal."},
{c:"senyals_perill",img:"/senyals/senyals-perill-08.svg",imgAlt:"Un triángulo con un signo de exclamación dentro significa",q:"Un triángulo con un signo de exclamación dentro significa:",o:["Peligro indefinido, a menudo acompañado de un panel explicativo","Prohibido todo tipo de vehículo","Zona de silencio","Obligación de parar en todas las intersecciones"],a:0,e:"Se utiliza para peligros que no tienen un pictograma específico; suele llevar un panel adicional."},
{c:"senyals_perill",img:"/senyals/senyals-perill-09.svg",imgAlt:"Un triángulo con el dibujo de un ferrocarril indica",q:"Un triángulo con el dibujo de un ferrocarril indica:",o:["Estación de tren cercana","Proximidad de un paso a nivel con barreras","Prohibido circular cerca de vías férreas","Zona de metro"],a:1,e:"Advierte de la proximidad de un paso a nivel, en este caso normalmente con barreras."},
{c:"senyals_perill",img:"/senyals/senyals-perill-10.svg",imgAlt:"Un triángulo con el dibujo de un semáforo indica",q:"Un triángulo con el dibujo de un semáforo indica:",o:["Proximidad de una instalación semafórica","Prohibido instalar semáforos","Zona sin semáforos","Semáforo averiado permanentemente"],a:0,e:"Avisa de la proximidad de un semáforo, sobre todo en tramos donde no se esperaría."},
{c:"senyals_perill",img:"/senyals/senyals-perill-11.svg",imgAlt:"Un triángulo con el dibujo de una flecha que se estrecha indica",q:"Un triángulo con el dibujo de una flecha que se estrecha indica:",o:["Ampliación de carriles inminente","Estrechamiento de calzada; hay que moderar la velocidad","Final de la obra","Carril bici a la derecha"],a:1,e:"Advierte de que la calzada se estrecha, lo que puede requerir reducir la velocidad y extremar la precaución."},
{c:"senyals_perill",img:"/senyals/senyals-perill-12.svg",imgAlt:"La señal de peligro con el dibujo de un montón de piedras o…",q:"La señal de peligro con el dibujo de un montón de piedras o desprendimientos indica:",o:["Zona de pícnic","Peligro de desprendimientos en la calzada","Obligación de llevar cadenas","Prohibido detenerse por el estado del terreno"],a:1,e:"Advierte del riesgo de caída de piedras o materiales sobre la vía, frecuente en zonas de montaña."},

// ---- senyals_indicacio ----
{c:"senyals_indicacio",img:"/senyals/senyals-indicacio-01.svg",imgAlt:"Un panel rectangular azul con una 'H' blanca indica",q:"Un panel rectangular azul con una 'H' blanca indica:",o:["Hotel cercano","Hospital","Autopista de acceso libre","Zona de aparcamiento para discapacitados"],a:1,e:"La 'H' sobre fondo azul indica la proximidad o dirección hacia un hospital."},
{c:"senyals_indicacio",img:"/senyals/senyals-indicacio-02.svg",imgAlt:"Una señal cuadrada azul con la figura de un peatón caminando indica",q:"Una señal cuadrada azul con la figura de un peatón caminando indica:",o:["Paso de peatones elevado","Camino o zona reservada para peatones","Prohibido el paso a peatones","Zona escolar"],a:1,e:"Las señales cuadradas o rectangulares azules suelen indicar información o servicios, en este caso vía para peatones."},
{c:"senyals_indicacio",img:"/senyals/senyals-indicacio-03.svg",imgAlt:"La señal que indica 'Autopista' (rectángulo azul con el dibujo…",q:"La señal que indica 'Autopista' (rectángulo azul con el dibujo esquemático de una vía rápida) marca:",o:["El comienzo del tramo de autopista","Área de descanso","Peaje obligatorio a 500 m","Fin del límite de velocidad"],a:0,e:"Este panel señaliza el inicio de un tramo de autopista, con sus normas específicas."},
{c:"senyals_indicacio",img:"/senyals/senyals-indicacio-04.svg",imgAlt:"Un panel con fondo verde y letras blancas se utiliza normalmente para…",q:"Un panel con fondo verde y letras blancas se utiliza normalmente para indicar:",o:["Direcciones dentro de casco urbano","Direcciones a través de vías rápidas o autovías","Zonas de peligro permanente","Prohibiciones temporales"],a:1,e:"El fondo verde se asocia a itinerarios por autovía o carretera de doble calzada."},
{c:"senyals_indicacio",img:"/senyals/senyals-indicacio-05.svg",imgAlt:"Un panel blanco con letras negras, situado en direcciones, suele…",q:"Un panel blanco con letras negras, situado en direcciones, suele indicar:",o:["Itinerario por carreteras convencionales","Solo zonas industriales","Prohibiciones de circulación","Límites de velocidad variables"],a:0,e:"El fondo blanco se usa habitualmente para itinerarios por carretera convencional."},

// ---- marques_vials ----
{c:"marques_vials",img:"/senyals/marques-vials-01.svg",imgAlt:"Una línea continua amarilla junto a la acera significa",q:"Una línea continua amarilla junto a la acera significa:",o:["Prohibida la parada y el estacionamiento","Prohibido solo el estacionamiento, se puede parar","Zona de carga libre","Paso de peatones"],a:0,e:"La línea amarilla continua en el bordillo prohíbe tanto la parada como el estacionamiento."},
{c:"marques_vials",img:"/senyals/marques-vials-02.svg",imgAlt:"Una línea longitudinal continua en la calzada significa",q:"Una línea longitudinal continua en la calzada significa:",o:["Se puede adelantar si hay visibilidad suficiente","Prohibido cruzarla o circular por encima para adelantar o girar a la izquierda","Solo se aplica a camiones","Marca meramente informativa"],a:1,e:"La línea continua no se puede traspasar, ni para adelantar ni para cambiar de carril, salvo excepciones muy concretas."},
{c:"marques_vials",img:"/senyals/marques-vials-03.svg",imgAlt:"Cuando la línea longitudinal es discontinua, esto significa",q:"Cuando la línea longitudinal es discontinua, esto significa:",o:["Se puede adelantar o cambiar de carril con precaución si las condiciones lo permiten","Está prohibido adelantar siempre","Indica el centro exacto de la calzada sin ningún otro efecto","Solo se puede circular por un carril"],a:0,e:"La línea discontinua permite cruzarla para adelantar o cambiar de carril cuando es seguro hacerlo."},
{c:"marques_vials",img:"/senyals/marques-vials-04.svg",imgAlt:"Una flecha blanca pintada en el suelo dentro de un carril indica",q:"Una flecha blanca pintada en el suelo dentro de un carril indica:",o:["Una simple decoración sin valor normativo","La dirección o direcciones obligatorias que debe seguir el vehículo en ese carril","Zona de giro prohibido","Límite de velocidad del carril"],a:1,e:"Las flechas de selección de carriles marcan las direcciones que se deben seguir obligatoriamente desde ese carril."},
{c:"marques_vials",img:"/senyals/marques-vials-05.svg",imgAlt:"Un paso de peatones se marca con",q:"Un paso de peatones se marca con:",o:["Líneas transversales continuas formando bandas","Una sola línea discontinua","Un triángulo amarillo en el suelo","Círculos blancos"],a:0,e:"El paso de peatones se representa con bandas blancas transversales en la calzada."},
{c:"marques_vials",img:"/senyals/marques-vials-06.svg",imgAlt:"Las marcas en zigzag amarillas en la acera indican",q:"Las marcas en zigzag amarillas en la acera indican:",o:["Zona de estacionamiento reservado para taxis","Prohibición de parada, a menudo delante de paradas de autobús o salidas de emergencia","Carril bici","Zona de velocidad reducida obligatoria"],a:1,e:"El zigzag amarillo marca zonas donde hay que mantener el acceso libre, como paradas de transporte público."},

// ---- normes_general ----
{c:"normes_general",q:"La distancia de seguridad con el vehículo de delante debe calcularse teniendo en cuenta, entre otros factores:",o:["Solo el color del vehículo propio","La velocidad, el estado de la vía y el tiempo de reacción","La marca del vehículo de delante","El número de personas en el vehículo"],a:1,e:"La distancia de seguridad depende de la velocidad, las condiciones de la vía y el tiempo de reacción del conductor."},
{c:"normes_general",q:"En un adelantamiento, una vez finalizado, el conductor debe:",o:["Mantenerse en el carril izquierdo indefinidamente","Reincorporarse a su carril tan pronto como sea posible sin entorpecer","Frenar bruscamente para avisar","Poner las luces largas de forma continua"],a:1,e:"Una vez completado el adelantamiento con seguridad, hay que volver al carril de circulación habitual."},
{c:"normes_general",q:"Circular por la izquierda en una vía de doble sentido sin necesidad es:",o:["Permitido si no hay tráfico","Una infracción, ya que se debe circular por la derecha","Obligatorio en curvas","Solo prohibido de noche"],a:1,e:"La norma general obliga a circular lo más a la derecha posible, salvo maniobras como el adelantamiento."},
{c:"normes_general",q:"En una rotonda, en general, tiene prioridad:",o:["El vehículo que entra en ella","El vehículo que ya circula dentro de la rotonda","El vehículo más grande","El que hace más ruido de claxon"],a:1,e:"Con carácter general, los vehículos que ya circulan dentro de la rotonda tienen preferencia sobre los que quieren entrar."},
{c:"normes_general",q:"Cuando dos vehículos llegan simultáneamente a una intersección sin señalización de prioridad, tiene preferencia:",o:["El que viene por la derecha","El que viene por la izquierda","El vehículo más rápido","El que toca el claxon primero"],a:0,e:"A falta de señalización, se aplica la regla general de prioridad del vehículo que viene por la derecha."},
{c:"normes_general",q:"El cambio de sentido (media vuelta) se puede hacer:",o:["En cualquier punto de la vía sin restricciones","Solo cuando esté permitido y sin crear peligro ni entorpecimiento","Únicamente de noche","Siempre que haya otro vehículo detrás"],a:1,e:"Hay que asegurarse de que la maniobra esté permitida en ese punto y de que no suponga riesgo."},
{c:"normes_general",q:"En caso de niebla densa, hay que circular con:",o:["Luces de cruce o antiniebla y velocidad reducida","Luces largas siempre","Sin luces para no deslumbrar","Luces de emergencia en marcha normal"],a:0,e:"Con niebla es recomendable el uso de luces de cruce o antiniebla y reducir la velocidad, aumentando la distancia de seguridad."},
{c:"normes_general",q:"El uso del teléfono móvil sin sistema de manos libres mientras se conduce es:",o:["Permitido si el vehículo está parado en un semáforo en rojo","Prohibido en general mientras el vehículo circula","Permitido siempre que sea breve","Solo prohibido en autopista"],a:1,e:"Manipular el móvil sin manos libres mientras se conduce está prohibido y es una distracción grave."},
{c:"normes_general",q:"En caso de cruzarse con un vehículo prioritario con señales luminosas y acústicas en marcha, el conductor debe:",o:["Ignorarlo si va por otro carril","Facilitarle el paso y, si es necesario, detenerse o desviarse","Acelerar para adelantarlo antes","Seguirlo para aprovechar el paso libre"],a:1,e:"Hay que facilitar el paso a los vehículos prioritarios en servicio, apartándose o deteniéndose si es necesario."},
{c:"normes_general",q:"La velocidad debe adaptarse siempre a:",o:["Únicamente el límite legal del tramo","Las condiciones de la vía, el tráfico, la visibilidad y el vehículo","La velocidad de los demás conductores","Lo que indique el copiloto"],a:1,e:"El límite legal es un máximo, pero la velocidad adecuada depende también de las condiciones reales de circulación."},
{c:"normes_general",q:"Cuando un vehículo circula por un carril de aceleración para incorporarse a una vía principal, los vehículos que ya circulan por ella:",o:["Deben facilitar la incorporación siempre que sea posible con seguridad","Deben detenerse completamente siempre","No tienen ninguna obligación","Deben acelerar para impedir el paso"],a:0,e:"Aunque el vehículo que se incorpora debe ceder el paso, los que ya circulan deben facilitar la maniobra cuando sea seguro hacerlo."},
{c:"normes_general",q:"Al circular por una rotonda, el uso de los intermitentes debe hacerse:",o:["Nunca, no hace falta señalizar dentro de una rotonda","Para indicar la salida que se va a tomar","Solo al entrar en ella","Solo si hay un agente regulando"],a:1,e:"Hay que indicar con el intermitente derecho la intención de salir de la rotonda para avisar al resto de usuarios."},
{c:"normes_general",q:"Circular demasiado cerca del vehículo de delante (conducción temeraria por proximidad) se conoce popularmente como:",o:["Zigzaguear","Ir 'pegado' al vehículo de delante","Hacer 'acoso vial'","No tiene nombre específico"],a:1,e:"Circular muy cerca, sin distancia de seguridad, se denomina coloquialmente ir 'pegado' al vehículo de delante."},
{c:"normes_general",q:"En caso de lluvia, la distancia de seguridad respecto a condiciones secas debe:",o:["Reducirse, ya que el freno funciona mejor mojado","Mantenerse igual siempre","Aumentarse, ya que la distancia de frenado crece","Es irrelevante"],a:2,e:"Con calzada mojada la distancia de frenado aumenta, por lo que hay que ampliar la distancia de seguridad."},
{c:"normes_general",q:"Un conductor que quiere girar a la izquierda en una intersección sin marcas específicas debe situarse:",o:["Lo más a la derecha posible de su carril","Lo más a la izquierda posible de su sentido de circulación, sin invadir el sentido contrario","En el centro exacto de la calzada","Es indiferente la posición"],a:1,e:"Para girar a la izquierda hay que situarse cerca del eje de la calzada o en el carril izquierdo correspondiente, sin invadir el sentido contrario."},
{c:"normes_general",q:"El hecho de circular en 'zigzag' entre carriles sin necesidad es:",o:["Una maniobra deportiva permitida en vías rápidas","Una infracción peligrosa que reduce la previsibilidad para los demás conductores","Obligatorio en caso de tráfico denso","Solo prohibido en autopista"],a:1,e:"Este tipo de conducción es peligroso y sancionable porque rompe la previsibilidad necesaria para la seguridad vial."},
{c:"normes_general",q:"Al llegar a un paso a nivel sin barreras con la señal luminosa roja intermitente activa, el conductor debe:",o:["Pasar rápidamente antes de que llegue el tren","Detenerse y no cruzar hasta que se apague la señal","Tocar el claxon y continuar","Reducir solo un poco la velocidad"],a:1,e:"La señal luminosa roja intermitente en un paso a nivel obliga a detenerse completamente."},
{c:"normes_general",q:"Cuando se conduce por una vía con hielo en la calzada, se recomienda:",o:["Frenazos bruscos para detenerse antes","Movimientos suaves en el volante, frenos y acelerador, evitando maniobras bruscas","Acelerar para atravesarla rápidamente","Circular con las luces largas siempre"],a:1,e:"Sobre hielo hay que evitar cualquier maniobra brusca que pueda provocar la pérdida de control del vehículo."},

// ---- alcohol_drogues ----
{c:"alcohol_drogues",q:"La tasa máxima de alcohol en sangre permitida para conductores con menos de dos años de experiencia es:",o:["0,5 g/l","0,3 g/l","0,8 g/l","No existe límite diferenciado"],a:1,e:"Los conductores noveles (menos de 2 años de carnet) tienen un límite más restrictivo de 0,3 g/l en sangre."},
{c:"alcohol_drogues",q:"El consumo de alcohol afecta principalmente:",o:["Solo la vista a corto plazo","La percepción, los reflejos y la capacidad de juicio","Únicamente la resistencia física","No tiene ningún efecto en la conducción si es poca cantidad"],a:1,e:"El alcohol altera la percepción del riesgo, ralentiza los reflejos y reduce la capacidad de tomar decisiones."},
{c:"alcohol_drogues",q:"Negarse a realizar la prueba de alcoholemia cuando lo requiere el agente es:",o:["Un derecho del conductor sin consecuencias","Una infracción grave, equiparable a dar positivo","Solo recomendable evitarlo","Legal si el conductor no ha bebido"],a:1,e:"La negativa a someterse a la prueba es en sí misma una infracción, con sanciones importantes."},
{c:"alcohol_drogues",q:"Los efectos de las drogas y ciertos medicamentos sobre la conducción:",o:["Son siempre menores que los del alcohol","Pueden alterar los reflejos y la percepción igual o más que el alcohol","Solo afectan si se toman antes de dormir","No tienen relación con la conducción"],a:1,e:"Muchas sustancias y medicamentos pueden alterar gravemente la capacidad de conducir con seguridad."},
{c:"alcohol_drogues",q:"Si un medicamento indica en el prospecto que puede afectar a la capacidad de conducir, el conductor debe:",o:["Tomarlo igualmente si la dosis es baja","Valorar su efecto y evitar conducir si se ve afectado","Conducir solo de día","Ignorar la advertencia"],a:1,e:"Hay que seguir las indicaciones del prospecto y abstenerse de conducir si el medicamento afecta a las capacidades."},

// ---- seguretat_passiva ----
{c:"seguretat_passiva",q:"El uso del cinturón de seguridad es obligatorio:",o:["Solo en carretera, no en ciudad","Para todos los ocupantes, delante y detrás, siempre que el vehículo disponga de él","Solo para el conductor","Solo en trayectos largos"],a:1,e:"Todos los ocupantes deben llevar cinturón siempre que el asiento disponga de él, tanto delante como detrás."},
{c:"seguretat_passiva",q:"Los niños deben viajar con un sistema de retención infantil:",o:["Hasta los 12 años si no alcanzan la altura mínima requerida","Solo hasta los 3 años","Nunca, si van en el asiento trasero","Solo en trayectos de autopista"],a:0,e:"Debe utilizarse el sistema de retención adecuado mientras el niño no cumpla los requisitos de altura/peso fijados."},
{c:"seguretat_passiva",q:"Un airbag frontal activo combinado con una sillita infantil orientada hacia atrás en el asiento delantero es:",o:["Siempre recomendable","Peligroso, por eso hay que desactivar el airbag en este caso","Indiferente para la seguridad","Obligatorio por ley"],a:1,e:"Con una sillita orientada hacia atrás en el asiento delantero, el airbag frontal debe estar desactivado por el riesgo que supone."},
{c:"seguretat_passiva",q:"El reposacabezas del asiento tiene como función principal:",o:["Mejorar la estética del vehículo","Reducir el riesgo de lesiones cervicales en caso de choque","Servir de apoyo para dormir","No tiene ninguna función de seguridad"],a:1,e:"El reposacabezas bien ajustado reduce el riesgo de lesión cervical (latigazo cervical) en colisiones."},
{c:"seguretat_passiva",q:"En caso de accidente, llevar el cinturón abrochado reduce principalmente:",o:["El consumo de combustible","El riesgo de salir despedido del habitáculo","El desgaste de los neumáticos","La necesidad de seguro"],a:1,e:"El cinturón evita que el ocupante sea lanzado contra el interior del vehículo o expulsado en caso de impacto."},

// ---- llums ----
{c:"llums",q:"Las luces de cruce deben utilizarse:",o:["Solo de noche en ciudad","Siempre que la visibilidad sea reducida o de noche, y en túneles","Nunca en carretera convencional","Solo cuando llueve muy fuerte"],a:1,e:"Hay que llevarlas encendidas de noche, en condiciones de baja visibilidad y siempre en túneles, aunque estén iluminados."},
{c:"llums",q:"Las luces largas deben cambiarse a cortas:",o:["Cuando otro vehículo circula en sentido contrario o le precede a corta distancia","Solo si un agente lo indica","Nunca, siempre deben mantenerse encendidas de noche","Solo en autopista"],a:0,e:"Para evitar deslumbrar a otros conductores, hay que pasar a luces de cruce ante vehículos que vienen de frente o cuando se circula detrás de otro."},
{c:"llums",q:"Las luces antiniebla traseras deben utilizarse:",o:["Siempre que sea de noche","Únicamente con niebla densa, lluvia intensa o nieve que reduzcan mucho la visibilidad","Con cualquier condición de lluvia leve","Nunca, están prohibidas"],a:1,e:"Estas luces, muy intensas, solo deben usarse cuando la visibilidad se reduce gravemente, para no deslumbrar innecesariamente."},
{c:"llums",q:"Las luces de emergencia (warning) deben activarse:",o:["Mientras se circula normalmente por autopista","En situaciones de peligro para otros usuarios, como una parada de emergencia","Para aparcar en doble fila de forma habitual","Siempre que llueva"],a:1,e:"Sirven para alertar a otros conductores de una situación de riesgo puntual, no para uso habitual."},
{c:"llums",q:"Circular con una luz fundida:",o:["No tiene ninguna consecuencia","Es una infracción y reduce la visibilidad y la seguridad propia y ajena","Solo es problema en zonas rurales","Se puede compensar acelerando"],a:1,e:"Una luz fundida reduce la visibilidad y la capacidad de los demás usuarios de detectar el vehículo, y es sancionable."},

// ---- autopista ----
{c:"autopista",q:"En autopista, el arcén se puede utilizar para circular:",o:["Con normalidad cuando hay mucho tráfico","Únicamente en caso de emergencia o avería, no para circular habitualmente","Siempre que se vaya a poca velocidad","Para hacer un adelantamiento rápido"],a:1,e:"El arcén está reservado para emergencias, averías o vehículos autorizados, no para circulación normal."},
{c:"autopista",q:"El acceso a una autopista se hace normalmente por:",o:["Un carril de incorporación que permite coger velocidad antes de unirse al tráfico","Directamente desde cualquier punto del arcén","Marcha atrás si te has pasado la salida","Deteniéndote en el carril derecho antes de entrar"],a:0,e:"El carril de incorporación o aceleración permite adaptar la velocidad antes de unirse al tráfico principal."},
{c:"autopista",q:"En autopista, si te pasas la salida que querías tomar, hay que:",o:["Dar marcha atrás por el arcén hasta la salida","Continuar hasta la siguiente salida disponible","Detenerse y esperar indicaciones","Cruzar la mediana para volver atrás"],a:1,e:"Nunca se debe circular en sentido contrario ni dar marcha atrás en autopista; hay que continuar hasta la próxima salida."},
{c:"autopista",q:"En autopista o autovía, la velocidad mínima establece, en general, el objetivo de:",o:["Evitar circular demasiado lento y entorpecer el tráfico fluido","No tiene ningún sentido una velocidad mínima","Obligar a ir siempre al límite máximo","Solo se aplica a camiones"],a:0,e:"Existe una velocidad mínima para evitar que vehículos muy lentos entorpezcan la fluidez del tráfico rápido."},
{c:"autopista",q:"Los vehículos que no pueden circular por autopista o autovía incluyen, entre otros:",o:["Motocicletas de cualquier cilindrada","Bicicletas, ciclomotores y peatones","Turismos con remolque ligero","Autocares"],a:1,e:"Bicicletas, ciclomotores, peatones y otros vehículos lentos tienen prohibido el acceso a autopistas y autovías."},
{c:"autopista",q:"En autopista, el carril izquierdo (el más a la izquierda) debe utilizarse:",o:["Para circular por él de forma habitual a cualquier velocidad","Preferentemente para adelantar, volviendo después a los carriles de la derecha","Únicamente para vehículos de emergencia","Para estacionar en caso de avería"],a:1,e:"El carril izquierdo se reserva básicamente para el adelantamiento, no para la circulación continuada."},
{c:"autopista",q:"Si un vehículo avería en un carril de autopista y no se puede mover, los ocupantes deben:",o:["Quedarse dentro del vehículo siempre","Salir por la puerta del lado de la vía y ponerse en un lugar seguro, fuera de la calzada si es posible","Empujar el vehículo entre el tráfico","Hacer autostop en medio de la calzada"],a:1,e:"Por seguridad, hay que salir del vehículo por el lado no expuesto al tráfico y situarse en una zona segura."},
{c:"autopista",q:"Los peajes de autopista deben abordarse:",o:["A la velocidad que se llevaba en la vía","Reduciendo la velocidad con suficiente antelación según la señalización del carril elegido","Acelerando para no perder tiempo","Sin necesidad de reducir nunca la velocidad"],a:1,e:"Hay que adaptar la velocidad al tipo de carril de peaje (manual, telepeaje, etc.) con suficiente antelación."},

// ---- documentacio ----
{c:"documentacio",q:"El seguro obligatorio de un vehículo cubre principalmente:",o:["Los daños que el vehículo pueda causar a terceros","Únicamente los daños al propio vehículo","Solo robos","Nada, es meramente informativo"],a:0,e:"El seguro obligatorio cubre la responsabilidad civil ante daños causados a terceros."},
{c:"documentacio",q:"Circular sin la ITV (Inspección Técnica de Vehículos) en vigor es:",o:["Legal si el vehículo es nuevo","Una infracción, ya que la ITV certifica que el vehículo cumple las condiciones técnicas exigidas","Solo problema si hay un accidente","Opcional para vehículos particulares"],a:1,e:"Circular sin la ITV en vigor es sancionable, y en algunos casos conlleva la inmovilización del vehículo."},
{c:"documentacio",q:"El permiso de conducir debe llevarse:",o:["Físicamente siempre, obligatoriamente, en el vehículo","Es recomendable poder acreditarlo, aunque existen medios electrónicos para hacerlo","No hace falta llevarlo nunca","Solo en trayectos internacionales"],a:1,e:"Hay que poder acreditar que se dispone del permiso vigente; existen sistemas digitales para hacerlo."},
{c:"documentacio",q:"En caso de accidente con daños materiales, es recomendable:",o:["Marcharse del lugar para no perder tiempo","Rellenar el parte amistoso de accidente e intercambiar datos con la otra parte","No hacer nada si los daños son pequeños","Llamar solo a la grúa"],a:1,e:"El parte amistoso facilita la gestión posterior con las aseguradoras y deja constancia de los hechos."},
{c:"documentacio",q:"Conducir sin el permiso correspondiente a la categoría del vehículo es:",o:["Una simple recomendación incumplida","Una infracción grave, ya que se necesita la habilitación legal para cada tipo de vehículo","Permitido si se tiene experiencia","Solo problema para menores de 18 años"],a:1,e:"Cada categoría de vehículo requiere el permiso correspondiente; conducir sin él es una infracción grave."},
{c:"documentacio",q:"El certificado de la ITV debe llevarse:",o:["En el vehículo o poder acreditarlo cuando se requiera","Nunca, no hace falta llevarlo a ningún sitio","Solo en trayectos internacionales","Únicamente los fines de semana"],a:0,e:"Hay que poder acreditar que el vehículo tiene la ITV en vigor cuando un agente lo requiera."},
{c:"documentacio",q:"En caso de cambio de titularidad de un vehículo, hay que:",o:["No hacer nada, el trámite es automático siempre","Notificar el cambio al organismo correspondiente en el plazo establecido","Esperar a la próxima ITV para notificarlo","Notificarlo solo si hay un accidente"],a:1,e:"El cambio de titularidad debe comunicarse dentro del plazo legal establecido para su validez administrativa."},
{c:"documentacio",q:"El seguro 'a todo riesgo' se diferencia del obligatorio en que:",o:["Son exactamente lo mismo","Amplía la cobertura, incluyendo por ejemplo daños propios, más allá del mínimo legal","Es más barato siempre","No cubre daños a terceros"],a:1,e:"El seguro a todo riesgo ofrece coberturas adicionales a las mínimas exigidas por ley, como los daños propios."},

// ---- mecanica ----
{c:"mecanica",q:"Una presión incorrecta de los neumáticos puede provocar:",o:["Mejor adherencia siempre","Mayor desgaste, peor frenada y riesgo de reventón","Ningún efecto notable","Menor consumo de combustible siempre"],a:1,e:"Una presión inadecuada afecta a la adherencia, la distancia de frenado y puede provocar averías graves como un reventón."},
{c:"mecanica",q:"El dibujo (banda de rodadura) mínimo legal de los neumáticos debe ser, como norma general:",o:["1,6 mm","0,5 mm","5 mm","No existe mínimo legal"],a:0,e:"La profundidad mínima legal del dibujo del neumático es de 1,6 mm en la mayor parte de la banda de rodadura."},
{c:"mecanica",q:"Un líquido de frenos en mal estado o insuficiente puede provocar:",o:["Mejor respuesta de los frenos","Pérdida de eficacia o fallo del sistema de frenado","No tiene relación con los frenos","Solo afecta a la dirección"],a:1,e:"El líquido de frenos es esencial para transmitir la fuerza al sistema; su mal estado compromete la frenada."},
{c:"mecanica",q:"Los retrovisores deben revisarse y ajustarse:",o:["Una vez al año en el taller","Antes de iniciar la marcha, cada vez que cambie el conductor o la carga","Nunca, se quedan fijos de fábrica","Solo en vehículos nuevos"],a:1,e:"Hay que ajustar los retrovisores siempre que haya un cambio de conductor o de condiciones que afecten a la visión posterior."},
{c:"mecanica",q:"Los frenos de disco, en general, en comparación con los de tambor:",o:["Disipan peor el calor","Suelen ofrecer mejor rendimiento y disipación de calor en frenadas intensas","No influyen en el rendimiento","Son siempre menos seguros"],a:1,e:"Los frenos de disco suelen enfriarse mejor y mantener el rendimiento en frenadas repetidas o intensas."},
{c:"mecanica",q:"Un nivel de aceite del motor demasiado bajo puede provocar:",o:["Mejor rendimiento del motor","Un desgaste prematuro y posibles averías graves del motor","Ningún efecto notable","Menos consumo de combustible"],a:1,e:"El aceite lubrica y refrigera el motor; un nivel insuficiente puede provocar daños graves y costosos."},
{c:"mecanica",q:"La comprobación de la presión de los neumáticos debe hacerse:",o:["Con los neumáticos calientes, después de un trayecto largo","Preferiblemente con los neumáticos fríos, antes de un trayecto largo","Una vez al año","Solo si parecen bajos a simple vista"],a:1,e:"La presión es más precisa con los neumáticos fríos, ya que el calor altera la lectura."},
{c:"mecanica",q:"El desgaste irregular de los neumáticos puede indicar:",o:["Nada relevante, es normal","Un problema de alineación, equilibrado o presión incorrecta","Que el vehículo es demasiado nuevo","Que hay que cambiar solo el aceite"],a:1,e:"Un desgaste irregular suele ser señal de un problema mecánico que conviene revisar por seguridad."},

// ---- primers_auxilis ----
{c:"primers_auxilis",q:"Ante un accidente, la primera actuación recomendada es:",o:["Mover siempre a los heridos inmediatamente","Señalizar el lugar y proteger la zona para evitar más accidentes","Marcharse a buscar ayuda sin avisar a nadie","Quitar el casco a un motorista herido siempre"],a:1,e:"La secuencia PAS (Proteger, Avisar, Socorrer) empieza por proteger la zona y evitar nuevos accidentes."},
{c:"primers_auxilis",q:"A un herido inconsciente que respira, en principio hay que colocarlo:",o:["Sentado con la cabeza hacia abajo","En posición lateral de seguridad","Boca abajo sin moverlo","De pie, si es posible"],a:1,e:"La posición lateral de seguridad ayuda a mantener la vía aérea libre en personas inconscientes que respiran."},
{c:"primers_auxilis",q:"En general, a un motorista herido tras una caída, el casco:",o:["Hay que quitárselo siempre inmediatamente","Solo hay que quitarlo si es imprescindible y por personal formado, para no agravar lesiones cervicales","Es irrelevante para su seguridad","Hay que romperlo con cualquier herramienta"],a:1,e:"Retirar el casco de forma incorrecta puede agravar posibles lesiones cervicales; solo debe hacerlo personal preparado si es estrictamente necesario."},
{c:"primers_auxilis",q:"El número de teléfono de emergencias general en Europa es:",o:["091","112","061 exclusivamente","080"],a:1,e:"El 112 es el número único de emergencias válido en toda la Unión Europea."},
{c:"primers_auxilis",q:"El acrónimo PAS en primeros auxilios de tráfico hace referencia a:",o:["Parar, Avanzar, Seguir","Proteger, Avisar, Socorrer","Prevenir, Actuar, Salvar","Subir, Ayudar, Salir"],a:1,e:"PAS resume el orden de actuación ante un accidente: Proteger la zona, Avisar a los servicios de emergencia y Socorrer a los heridos."},
{c:"primers_auxilis",q:"Ante una hemorragia externa importante, la primera medida recomendada suele ser:",o:["Aplicar un torniquete inmediatamente siempre","Hacer presión directa sobre la herida con un paño limpio","No tocar la herida en ningún caso","Lavar la herida con agua fría abundante"],a:1,e:"La presión directa con un paño limpio suele ser la primera medida para controlar una hemorragia externa."},
{c:"primers_auxilis",q:"Al señalizar un accidente en la carretera de noche, es recomendable:",o:["Utilizar el chaleco reflectante y colocarse detrás de la barrera de seguridad si la hay","Quedarse en medio de la calzada para avisar con los brazos","Apagar todas las luces del vehículo para no deslumbrar","Usar solo el claxon para avisar"],a:0,e:"Hay que hacerse visible con el chaleco y situarse en un lugar seguro, protegido si es posible, mientras se avisa del peligro."},

// ---- factor_humans ----
{c:"factor_humans",q:"La fatiga al volante afecta principalmente:",o:["Solo la resistencia muscular","El tiempo de reacción, la atención y la capacidad de decisión","La velocidad máxima del vehículo","No afecta si el trayecto es corto"],a:1,e:"El cansancio reduce la capacidad de atención y ralentiza los reflejos, aumentando el riesgo de accidente."},
{c:"factor_humans",q:"En trayectos largos, se recomienda hacer una pausa:",o:["Cada 8 horas de conducción seguida","Cada 2 horas aproximadamente o al notar síntomas de cansancio","Solo si el copiloto lo pide","Nunca, para no perder tiempo"],a:1,e:"Es recomendable descansar periódicamente, aproximadamente cada dos horas, para mantener la atención."},
{c:"factor_humans",q:"Las distracciones más frecuentes en la conducción incluyen:",o:["Mirar por el retrovisor","El uso del móvil, comer o manipular el navegador mientras se circula","Llevar el cinturón abrochado","Mantener las manos en el volante"],a:1,e:"Manipular dispositivos, comer u otras actividades que desvían la atención de la vía son causas frecuentes de accidentes."},
{c:"factor_humans",q:"El estado emocional del conductor (rabia, estrés, ansiedad):",o:["No influye en la conducción","Puede alterar la capacidad de juicio y favorecer conductas de riesgo","Solo afecta si se conduce de noche","Mejora la concentración"],a:1,e:"Los estados emocionales intensos pueden llevar a conducir de forma más agresiva o menos atenta."},
{c:"factor_humans",q:"Conducir con un sueño excesivo tiene un efecto comparable a:",o:["No tiene ningún efecto apreciable","Conducir bajo los efectos del alcohol, por la pérdida de reflejos y atención","Mejorar la concentración","Solo afecta a la temperatura corporal"],a:1,e:"El sueño excesivo puede alterar los reflejos y la atención de forma similar a la intoxicación alcohólica."},
{c:"factor_humans",q:"Escuchar música a un volumen muy alto mientras se conduce puede:",o:["Mejorar la concentración siempre","Dificultar oír señales acústicas importantes, como sirenas","No tener ningún efecto","Ser obligatorio para mantenerse despierto"],a:1,e:"Un volumen excesivo puede impedir oír avisos sonoros relevantes, como sirenas de vehículos de emergencia."},

// ---- sancions ----
{c:"sancions",q:"El sistema de permiso por puntos:",o:["No tiene relación con las infracciones cometidas","Resta puntos del saldo del conductor según la gravedad de la infracción cometida","Solo afecta a conductores profesionales","Suma puntos por cada kilómetro recorrido"],a:1,e:"Cada infracción grave o muy grave conlleva la pérdida de un número determinado de puntos del permiso."},
{c:"sancions",q:"Un conductor novel, durante los primeros años con el permiso, suele tener:",o:["Más puntos iniciales que un conductor experimentado","Menos puntos iniciales en su saldo, como medida de prevención","Los mismos puntos sin diferencias","Ningún límite de puntos"],a:1,e:"Los conductores noveles tienen un saldo de puntos inicial inferior hasta consolidar la experiencia."},
{c:"sancions",q:"Superar el límite de velocidad en un tramo determinado:",o:["Nunca conlleva pérdida de puntos, solo multa económica","Puede conllevar sanción económica y, según el exceso, pérdida de puntos","Es irrelevante si no hay radar","Solo se sanciona en autopista"],a:1,e:"Según el porcentaje de exceso de velocidad, la infracción puede conllevar multa y pérdida de puntos."},
{c:"sancions",q:"No llevar el cinturón de seguridad abrochado estando obligado a ello es:",o:["Una infracción leve sin consecuencias en puntos","Una infracción que puede conllevar multa y pérdida de puntos","Una recomendación, no una obligación legal","Solo aplicable al conductor, nunca a los pasajeros"],a:1,e:"No llevar el cinturón cuando es obligatorio conlleva sanción económica y pérdida de puntos del carnet."},
{c:"sancions",q:"Utilizar el móvil sin manos libres mientras se circula:",o:["No tiene sanción si se hace con el vehículo parado en un semáforo","Se considera infracción grave con pérdida de puntos","Solo es sancionable en autopista","Es legal si se hace brevemente"],a:1,e:"El uso del móvil sin manos libres durante la circulación se considera infracción grave."},

// ---- estacionament ----
{c:"estacionament",q:"Se entiende por 'parada' la inmovilización del vehículo:",o:["Durante más de dos horas","Durante un tiempo breve, sin que el conductor lo abandone, por ejemplo para que suba o baje alguien","Siempre con el motor apagado y las llaves quitadas","Solo en zonas señalizadas"],a:1,e:"La parada es una inmovilización breve en la que el conductor permanece en el vehículo o cerca, listo para moverlo."},
{c:"estacionament",q:"Se entiende por 'estacionamiento' la inmovilización del vehículo:",o:["Que dura más que el tiempo necesario para que suban o bajen personas o se cargue algo, y el conductor puede alejarse de él","Solo cuando el motor está encendido","Únicamente en aparcamientos privados","Cuando el vehículo lleva las luces encendidas"],a:0,e:"El estacionamiento implica dejar el vehículo inmovilizado durante más tiempo, sin necesidad de que el conductor permanezca en él."},
{c:"estacionament",q:"Estacionar delante de una salida de emergencia o boca de incendios es:",o:["Permitido si es por poco rato","Prohibido siempre, para no entorpecer un servicio de emergencia","Solo prohibido de noche","Permitido con autorización verbal de un vecino"],a:1,e:"Estas zonas deben permanecer siempre libres para garantizar el acceso en caso de emergencia."},
{c:"estacionament",q:"En una vía con pendiente, al estacionar sin marcha puesta, se recomienda:",o:["No hace falta hacer nada especial","Girar las ruedas hacia el bordillo y poner una marcha o el freno de mano","Dejar el vehículo en punto muerto siempre","Quitar el freno de mano para evitar desgaste"],a:1,e:"Girar las ruedas y dejar puesta una marcha (o accionado el freno de mano) evita que el vehículo se deslice pendiente abajo."},
{c:"estacionament",q:"Estacionar en un carril reservado para transporte público (carril bus) fuera de su horario de uso:",o:["Siempre es correcto","Puede estar permitido o no según la señalización específica del tramo","Nunca está permitido, en ninguna circunstancia","Es obligatorio hacerlo para no molestar en otros carriles"],a:1,e:"Depende de la señalización concreta del tramo; algunos carriles bus permiten estacionar fuera del horario de servicio y otros no."},
{c:"estacionament",q:"Dejar un vehículo estacionado de forma que dificulte la salida de otro vehículo correctamente aparcado es:",o:["Permitido si es por poco rato","Una infracción, ya que hay que evitar entorpecer a otros vehículos","Solo problema en zonas azules","Legal si se dejan las luces de emergencia"],a:1,e:"No se puede estacionar de forma que impida o dificulte la salida de otros vehículos ya estacionados correctamente."},

// ---- usuaris_vulnerables ----
{c:"usuaris_vulnerables",q:"Ante un paso de peatones sin semáforo donde hay peatones esperando para cruzar, el conductor debe:",o:["Pasar rápidamente antes de que empiecen a cruzar","Ceder el paso y, si es necesario, detenerse para dejarlos cruzar con seguridad","Tocar el claxon para que esperen","Avanzar solo si no hay ningún peatón en medio de la calzada"],a:1,e:"Hay que ceder el paso a los peatones que esperan o ya están cruzando por un paso señalizado."},
{c:"usuaris_vulnerables",q:"Para adelantar a un ciclista, el conductor de un turismo debe:",o:["Pasar lo más cerca posible para ahorrar tiempo","Dejar una distancia lateral de seguridad suficiente","No hace falta reducir la velocidad en ningún caso","Hacerlo solo si el ciclista se aparta"],a:1,e:"Hay que dejar una distancia lateral mínima de seguridad al adelantar a ciclistas, reduciendo la velocidad si procede."},
{c:"usuaris_vulnerables",q:"Los vehículos de movilidad personal (VMP, como los patinetes eléctricos):",o:["Pueden circular siempre por la acera a cualquier velocidad","Están sujetos a normas específicas y, en general, no pueden circular por aceras ni autopistas","No tienen ninguna normativa aplicable","Tienen siempre prioridad sobre los peatones"],a:1,e:"Los VMP tienen normativa propia que regula su uso, restringiendo la circulación por aceras y vías rápidas."},
{c:"usuaris_vulnerables",q:"Al acercarse a un autobús escolar detenido con las luces de advertencia encendidas, el conductor debe:",o:["Adelantarlo sin reducir velocidad","Extremar la precaución por la posible presencia de niños cruzando","Tocar el claxon para avisar de que pasa","Ignorarlo si no hay niños visibles"],a:1,e:"Hay que extremar las precauciones ante transportes escolares, ya que pueden cruzar niños de forma inesperada."},
{c:"usuaris_vulnerables",q:"Al acercarse a una parada de autobús con un autobús detenido recogiendo pasajeros, hay que:",o:["Adelantarlo sin ninguna precaución especial","Extremar la precaución por la posible presencia de peatones cruzando por delante o por detrás","Tocar el claxon para que arranque","Adelantarlo siempre por el arcén"],a:1,e:"Los peatones pueden cruzar de forma inesperada por delante o por detrás del autobús detenido, por lo que hay que extremar la precaución."},
{c:"usuaris_vulnerables",q:"Un ciclista que circula por la calzada, en ausencia de carril bici:",o:["Debe circular siempre por la acera","Tiene derecho a ocupar el carril con las mismas normas generales que el resto de vehículos","No tiene ningún derecho a circular por la calzada","Debe circular siempre en sentido contrario al tráfico"],a:1,e:"El ciclista es un usuario más de la vía y, en ausencia de carril bici, puede circular por el carril siguiendo las normas generales."},

// ---- prioritat ----
{c:"prioritat",q:"En una intersección, una señal de 'Ceda el paso' obliga a:",o:["Detenerse siempre, haya tráfico o no","Dejar pasar a los vehículos que circulan por la vía a la que se incorpora, deteniéndose si es necesario","Avanzar sin mirar si no hay semáforo","Tocar el claxon antes de entrar"],a:1,e:"Ceda el paso obliga a dejar circular a los vehículos de la vía preferente, deteniéndose si es necesario para hacerlo con seguridad."},
{c:"prioritat",q:"Un vehículo que sale de un aparcamiento o de una vía privada para incorporarse a la calzada:",o:["Tiene siempre prioridad sobre los vehículos de la vía","Debe ceder el paso a los vehículos que ya circulan por la vía principal","Puede incorporarse sin mirar","Tiene prioridad solo si va más rápido"],a:1,e:"Los vehículos que salen de zonas como aparcamientos o vías privadas deben ceder el paso a la circulación normal."},
{c:"prioritat",q:"En ausencia de señales, en un cruce entre una vía normal y otra claramente secundaria o de salida de una finca, en general:",o:["Siempre tiene prioridad el vehículo más grande","Tiene preferencia el vehículo que circula por la vía principal","No hay ninguna norma aplicable","Tiene preferencia quien llega primero sea como sea"],a:1,e:"Con carácter general la vía de características principales tiene preferencia sobre una vía claramente secundaria."},
{c:"prioritat",q:"Un vehículo en maniobra de marcha atrás respecto a otro que circula normalmente:",o:["Tiene siempre preferencia porque va más lento","Debe ceder el paso, ya que las maniobras como la marcha atrás pierden la prioridad","No hay regla, depende del claxon","Tiene preferencia si es más grande"],a:1,e:"Los vehículos que realizan maniobras como la marcha atrás deben ceder el paso al resto de la circulación."},
{c:"prioritat",q:"En un carril de un único sentido que se divide en dos por un obstáculo, cuando dos vehículos llegan a la vez en sentidos opuestos:",o:["Tiene preferencia el que circula por el lado en que el obstáculo no le obliga a invadir el carril contrario","Siempre pasa primero el más rápido","Deben detenerse ambos indefinidamente","Tiene preferencia el vehículo de mayor tonelaje"],a:0,e:"Tiene preferencia de paso el vehículo que no tiene que ocupar parte del carril contrario para esquivar el obstáculo."},
// ---- carrils (VAO, reversible, addicional, bus) ----
{c:"carrils",q:"Un carril reversible es aquel que:",o:["Solo puede usarse en sentido contrario al resto de la vía","Puede cambiar de sentido de circulación según las necesidades del tráfico","Está reservado permanentemente a vehículos lentos","Solo existe en autopistas de peaje"],a:1,e:"El carril reversible cambia su sentido de circulación según la hora o la densidad del tráfico; está señalizado con paneles luminosos que indican en cada momento si se puede usar."},
{c:"carrils",q:"Un carril reversible se señaliza normalmente mediante:",o:["Una línea continua amarilla en ambos bordes","Marcas viales de doble línea discontinua y paneles luminosos sobre el carril","Solo conos en la calzada","Únicamente una señal circular azul"],a:1,e:"El carril reversible se delimita con doble línea discontinua a ambos lados y su sentido se indica con paneles luminosos (aspa roja o flecha verde)."},
{c:"carrils",q:"Si sobre un carril aparece un aspa roja luminosa, significa que:",o:["El carril está reservado a vehículos pesados","El carril está cerrado a la circulación y no se puede usar","Se puede circular pero a velocidad reducida","Es el carril de incorporación obligatorio"],a:1,e:"El aspa roja indica carril cerrado: hay que abandonarlo cuanto antes con seguridad y pasar a un carril con flecha verde."},
{c:"carrils",q:"Las siglas VAO en un carril hacen referencia a:",o:["Vehículo de Alta Ocupación","Vía de Acceso Obligatorio","Vehículo de Alta Ocupación solo en autopista de peaje","Velocidad Adaptada Obligatoria"],a:0,e:"VAO significa Vehículo de Alta Ocupación: un carril reservado a vehículos con un número mínimo de ocupantes, indicado en la señalización."},
{c:"carrils",q:"Para poder circular por un carril VAO señalizado para 2 o más ocupantes hace falta:",o:["Ir solo el conductor si el vehículo es eléctrico","Llevar en el vehículo al menos el número de ocupantes indicado en la señal","Circular siempre por encima de 100 km/h","Tener autorización especial de la DGT"],a:1,e:"El carril VAO exige llevar como mínimo los ocupantes indicados en la señalización; motocicletas y algunos vehículos concretos pueden estar autorizados aunque vayan solos."},
{c:"carrils",q:"Un carril adicional en una vía de doble sentido está destinado principalmente a:",o:["Aparcar en pendiente","Facilitar que los vehículos lentos sean adelantados con seguridad en subidas","Circular en sentido contrario","Uso exclusivo de vehículos de emergencia"],a:1,e:"El carril adicional (habitual en rampas) permite que los vehículos lentos se aparten a la derecha para que el resto pueda adelantar con seguridad."},
{c:"carrils",q:"Circulando por una vía con carril adicional en una subida, un vehículo lento debe:",o:["Mantenerse en el carril izquierdo","Utilizar el carril adicional de la derecha para facilitar el adelantamiento","Detenerse en el arcén hasta que pasen los demás","Acelerar hasta el límite máximo"],a:1,e:"El vehículo lento debe usar el carril adicional de la derecha para no entorpecer al resto de la circulación."},
{c:"carrils",q:"Un carril BUS-VAO permite la circulación de:",o:["Solo autobuses, en ningún caso turismos","Autobuses y vehículos que cumplan la ocupación mínima señalizada","Cualquier vehículo si va con prisa","Solo taxis"],a:1,e:"El carril BUS-VAO combina ambos usos: autobuses y vehículos de alta ocupación que cumplan el mínimo de ocupantes indicado."},
{c:"carrils",q:"Cuando un panel luminoso muestra una flecha verde sobre un carril, indica que:",o:["El carril está abierto a la circulación en ese sentido","Hay que reducir la velocidad a la mitad","Es un carril exclusivo de vehículos prioritarios","El carril se cerrará en 100 metros"],a:0,e:"La flecha verde indica que el carril está abierto y se puede circular por él en el sentido de la marcha."},
{c:"carrils",q:"En una vía urbana, invadir un carril bus sin estar autorizado:",o:["Es legal si no viene ningún autobús","Constituye una infracción sancionable","Solo se sanciona en hora punta","Está permitido para girar a la derecha en cualquier punto"],a:1,e:"El carril bus está reservado al transporte público y a los vehículos autorizados; invadirlo sin autorización es una infracción, salvo para incorporarse o girar donde la señalización lo permita."},
{c:"carrils",q:"En un tramo con carril reversible activo en sentido contrario al tuyo, debes:",o:["Usarlo igualmente si hay poco tráfico","No invadirlo bajo ningún concepto","Circular por él solo para adelantar","Usarlo únicamente de noche"],a:1,e:"Invadir un carril reversible habilitado en sentido contrario supone circular de frente contra el tráfico: es extremadamente peligroso y está prohibido."},

// ---- velocitat ----
{c:"velocitat",q:"La velocidad máxima genérica para turismos en autopista y autovía es:",o:["100 km/h","120 km/h","130 km/h","110 km/h"],a:1,e:"En autopistas y autovías el límite genérico para turismos y motocicletas es de 120 km/h, salvo señalización que indique otra cosa."},
{c:"velocitat",q:"En carretera convencional (fuera de poblado, con una calzada por sentido), la velocidad máxima genérica para turismos es:",o:["90 km/h","100 km/h","80 km/h","120 km/h"],a:0,e:"En las carreteras convencionales el límite genérico para turismos y motocicletas es de 90 km/h."},
{c:"velocitat",q:"En vías urbanas de un único carril por sentido, la velocidad máxima genérica es:",o:["50 km/h","30 km/h","20 km/h","40 km/h"],a:1,e:"En vías urbanas de un solo carril por sentido el límite es de 30 km/h; en las de dos o más carriles por sentido, 50 km/h."},
{c:"velocitat",q:"En una vía urbana con dos o más carriles por sentido de circulación, el límite genérico es:",o:["30 km/h","50 km/h","60 km/h","40 km/h"],a:1,e:"Las vías urbanas con dos o más carriles por sentido mantienen el límite de 50 km/h."},
{c:"velocitat",q:"En una calle con plataforma única (acera y calzada al mismo nivel), la velocidad máxima es:",o:["30 km/h","20 km/h","10 km/h","50 km/h"],a:1,e:"En las vías de plataforma única, donde peatones y vehículos comparten el espacio, el límite es de 20 km/h."},
{c:"velocitat",q:"Para adelantar en una carretera convencional, ¿se puede superar el límite de velocidad del tramo?",o:["Sí, hasta 20 km/h por encima","No, nunca se puede superar el límite establecido","Sí, si el adelantamiento dura menos de 10 segundos","Sí, siempre que no haya radar"],a:1,e:"Desde la reforma del reglamento no se permite rebasar el límite de velocidad para adelantar: hay que completar la maniobra sin superarlo."},
{c:"velocitat",q:"La velocidad mínima genérica en autopistas y autovías es, con carácter general:",o:["40 km/h","60 km/h","80 km/h","No existe mínimo"],a:1,e:"Con carácter general, en autopistas y autovías no se puede circular por debajo de 60 km/h, para no entorpecer la fluidez del tráfico."},
{c:"velocitat",q:"Un turismo que arrastra un remolque ligero por autovía tiene un límite genérico de:",o:["120 km/h","90 km/h","80 km/h","100 km/h"],a:1,e:"Los turismos con remolque ven reducido su límite: 90 km/h en autopista y autovía, y 80 km/h en carretera convencional."},
{c:"velocitat",q:"Los límites genéricos de velocidad se aplican:",o:["Siempre, aunque haya señales que indiquen otra cosa","Solo cuando no hay una señal que fije un límite distinto para ese tramo","Únicamente de noche","Solo en días laborables"],a:1,e:"Los límites genéricos son los que rigen por defecto; una señal específica de velocidad prevalece sobre ellos en ese tramo."},
{c:"velocitat",q:"Circular muy por debajo del límite sin causa justificada en una vía rápida:",o:["Es siempre lo más seguro","Puede constituir una infracción por entorpecer la circulación","Está recomendado para conductores noveles","Solo es problema si hay niebla"],a:1,e:"Conducir a velocidad anormalmente reducida sin motivo justificado entorpece el tráfico y puede ser sancionable."},
{c:"velocitat",q:"En una travesía (tramo de carretera que atraviesa un poblado), la velocidad:",o:["Se mantiene igual que en la carretera","Se rige por los límites de vía urbana o por la señalización específica","Es siempre de 90 km/h","No tiene límite si no hay señales"],a:1,e:"Al entrar en poblado se aplican los límites urbanos o la velocidad concreta que indique la señalización de la travesía."},
];

/* ---------- PRNG determinista ---------- */
export function mulberry32(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function shuffleWithRng(arr, rng) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function passThreshold(n) {
  return Math.max(1, Math.round(n * 0.1)); // errores permitidos (10%, como el 3/30 real)
}

/* ids (índices en Q) que forman el examen numerado `examNum`, siempre los mismos */
export function buildExamIds(examNum) {
  const rng = mulberry32(1000 + examNum * 97);
  return shuffleWithRng(Q.map((_, i) => i), rng).slice(0, 30);
}

/* construye la pregunta renderizable (con opciones mezcladas) a partir de un id */
export function buildQuestionFromIndex(idx, seed) {
  const item = Q[idx];
  const optOrder = shuffleWithRng([0, 1, 2, 3], mulberry32(idx * 13 + seed * 7));
  return {
    idx,
    cat: item.c,
    text: item.q,
    options: optOrder.map((o) => item.o[o]),
    correct: optOrder.indexOf(item.a),
    exp: item.e,
  };
}

export function buildExamQuestions(ids, seed) {
  return ids.map((idx) => buildQuestionFromIndex(idx, seed));
}

/* mezcla estable de las preguntas falladas, para repartirlas en bloques de hasta 30 */
export function shuffledFailedIds(failedIds) {
  const seed = failedIds.reduce((a, b) => a + b, 777);
  return shuffleWithRng(failedIds, mulberry32(seed));
}

export function reviewChunkIds(failedIds, chunkIndex) {
  return shuffledFailedIds(failedIds).slice(chunkIndex * 30, chunkIndex * 30 + 30);
}
